"""
PDF report generation for Hack4Health clinical AI reports.
Uses fpdf2 library for lightweight PDF creation with no system binary dependencies.
"""
import os
import datetime
from fpdf import FPDF


class ClinicalReportPDF(FPDF):
    """Custom PDF class with medical disclaimer footer on every page."""

    def footer(self):
        """Renders the medical disclaimer footer at the bottom of each page."""
        self.set_y(-20)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(128, 128, 128)
        disclaimer = (
            "This report is generated by an AI system and is not a substitute for "
            "professional clinical judgment, diagnosis, or treatment. "
            "Always consult a qualified healthcare professional."
        )
        self.multi_cell(0, 4, disclaimer, align="C")


def generate_pdf(
    patient_id: str,
    patient_name: str,
    modality: str,
    clinical_context: str,
    report_data: dict,
    inference_time: float,
    token_count: int,
    image_path: str = None,
) -> bytes:
    """
    Generates a premium, clean PDF clinical report.

    Args:
        patient_id: Patient identifier string.
        patient_name: Patient name string.
        modality: Imaging modality (e.g., "X-ray").
        clinical_context: Clinical context provided by the clinician.
        report_data: Dict with keys: findings, differential_diagnosis,
                     recommended_actions, clinical_notes, narrative.
        inference_time: Model inference time in seconds.
        token_count: Approximate number of tokens generated.
        image_path: Optional path to the uploaded image file.

    Returns:
        The PDF document as bytes.
    """
    pdf = ClinicalReportPDF()
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()

    # ── Header ──────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 12, "Hack4Health", ln=False, align="C")
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, "Clinical AI Report", ln=True, align="C")

    # Teal horizontal line
    pdf.set_draw_color(0, 168, 132)
    pdf.set_line_width(0.6)
    pdf.line(10, pdf.get_y() + 2, 200, pdf.get_y() + 2)
    pdf.ln(8)

    # ── Patient Information ──────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "Patient Information", ln=True)
    pdf.set_draw_color(220, 220, 220)
    pdf.set_line_width(0.2)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(60, 60, 60)

    info_fields = [
        ("Patient ID", str(patient_id or "N/A")),
        ("Patient Name", str(patient_name or "N/A")),
        ("Modality", str(modality)),
        ("Date / Time", datetime.datetime.now().strftime("%Y-%m-%d  %H:%M:%S")),
    ]

    for label, value in info_fields:
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(42, 6, f"{label}:", border=0)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 6, value, border=0, ln=True)

    pdf.ln(4)

    # ── Clinical Context ─────────────────────────────────────
    if clinical_context:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 8, "Clinical Context", ln=True)
        pdf.set_draw_color(220, 220, 220)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(0, 5, str(clinical_context))
        pdf.ln(4)

    # ── Embedded Image ───────────────────────────────────────
    if image_path and os.path.exists(image_path):
        try:
            pdf.image(image_path, x=20, w=170)
            pdf.ln(6)
        except Exception as e:
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(180, 80, 80)
            pdf.cell(0, 5, f"[Image could not be embedded: {e}]", ln=True)
            pdf.ln(3)

    # ── Report Sections ──────────────────────────────────────
    sections = [
        ("Findings", report_data.get("findings", "")),
        ("Differential Diagnosis", report_data.get("differential_diagnosis", "")),
        ("Recommended Actions", report_data.get("recommended_actions", "")),
        ("Clinical Notes", report_data.get("clinical_notes", "")),
    ]

    for title, content in sections:
        if content:
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 8, title, ln=True)
            pdf.set_draw_color(0, 168, 132)
            pdf.set_line_width(0.3)
            pdf.line(10, pdf.get_y(), 60, pdf.get_y())
            pdf.ln(3)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(0, 5, str(content))
            pdf.ln(5)

    # ── Narrative Section ────────────────────────────────────
    narrative = report_data.get("narrative", "")
    if narrative:
        pdf.set_draw_color(200, 200, 200)
        pdf.set_line_width(0.2)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)

        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 8, "Free-Form Clinical Narrative", ln=True)
        pdf.set_draw_color(0, 168, 132)
        pdf.set_line_width(0.3)
        pdf.line(10, pdf.get_y(), 80, pdf.get_y())
        pdf.ln(3)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(50, 50, 50)
        pdf.multi_cell(0, 5, str(narrative))
        pdf.ln(5)

    # ── Inference Stats ──────────────────────────────────────
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(140, 140, 140)
    pdf.cell(
        0,
        5,
        f"Inference Time: {inference_time:.2f}s  |  Tokens: {token_count}  |  "
        f"Engine: HealthGPT-Pro-8B (MLX, 4-bit)  |  Device: Apple Silicon",
        ln=True,
        align="L",
    )

    return bytes(pdf.output())
